name: Build for armv7

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the simple http server for gcc7-armv7
        uses: ./.github/actions/xcompile-in-conan-docker
        with:
          target-duet: gcc7-armv7
      - name: Uploading http-server artifact
        uses: actions/upload-artifact@v1
        with:
          name: http-server-gcc7-armv7
          path: ./build-gcc7-armv7/bin/http-server

  sanity-runner:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: http-server-gcc7-armv7
      - run: docker run --rm --privileged -v `pwd`:/home/arm multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: 'uname -a'
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: 'chmod +x ./http-server-gcc7-armv7/http-server'
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: './http-server-gcc7-armv7/http-server --help'
        
